CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  fio TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pension (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  amount FLOAT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
